### PR TITLE
Update Kubernetes version to 1.20.6

### PR DESCRIPTION
**Pull request by schlapzz**
Kubernetes Version to 1.20.6 and Golang Version to 1.15

Docker image for testing:
docker.io/swisstxt/cloudstack-kubernetes-provider:v1.20.6-ae73327f

### CODE REVIEW

**Comment by davidjumani** [comment]
@joschi36 Could you provide the iso you used to deploy a 1.20 env ?

**Comment by joschi36** [comment]
> @joschi36 Could you provide the iso you used to deploy a 1.20 env ?

@davidjumani Hey I'm not sure what you are referring to, but maybe the CloudStack Kubernetes Service?
We are using an own installation for multiple years now and I just updated my test cluster manually to 1.20.

@rhtyd I would opt to release this in a new version, so we can finally release our first version that the people can use.

**Comment by rhtyd** [comment]
Any update on this - can this be merged?

**Comment by davidjumani** [comment]
@rhtyd @joschi36 Can this be merged after 1.0 is released? Since there only exist isos for 1.16. Post release isos for 1.18, 1.20 can be created and tested

**Comment by joschi36** [comment]
@rhtyd @davidjumani I also vote to move this out of v1.0, so we finally can get the first release done. Never intended to be in 1.0

**Comment by rhtyd** [comment]
Okay removing from 1.0 milestone

**Comment by hrak** [comment]
This PR can be closed (already merged as part of #44 )

**Pull request closed without merging**
