### PR TITLE
Some fixes for Go 1.13

### PR DESCRIPTION
**Pull request by onitake**
* Bumped Go min version to 1.13 to avoid incompatible builds
* Fixed go-cloudstack module version (now correctly semantically versioned) -> Reported here https://github.com/xanzy/go-cloudstack/issues/125 - but was already fixed by the author
* Fixed k8s module checksum -> Probably this issue https://github.com/kubernetes/kubernetes/issues/69040

### CODE REVIEW

**Comment by rhtyd** [comment]
@onitake can you update this and see if we should consider Go v1.15 now?

**Comment by rhtyd** [comment]
@onitake can you advise when this is ready for merging, thnx

**Comment by onitake** [comment]
Hi @rhtyd it's actually not necessary to require Go 1.15.
go.mod should reflect the minimum version required to build the module, which is 1.13. See here: https://golang.org/doc/go1.12#modules

But I'll gladly update the Dockerfile so 1.15 is used for standard builds. Are you ok if I commit this into this PR?

On another note:
Since Go modules are pretty much the standard now, it would probably be ok to drop the vendored dependencies. What do you think? go.mod and go.sum will ensure the right trees are fetched anyway.

**Comment by rhtyd** [comment]
I'm okay with the changes, but unable to review or test this. I can merge if you or any other collaborators can do a single review/lgtm and show any tests. Happy to merge then, thanks.

**Comment by onitake** [comment]
Thanks, @rhtyd .
It would be good if we have some automated builds/tests anyway. These kinds of PRs should be easy to test.

**Comment by rhtyd** [comment]
@onitake we've Travis integration for all apache repos, can we leverage that?

**Comment by rhtyd** [comment]
@onitake you may log a ticket with ASF INFRA (https://issues.apache.org/jira/projects/INFRA) to enable Travis support https://travis-ci.org/github/apache/cloudstack-kubernetes-provider

**Comment by onitake** [comment]
I think I can write a quick .travis.yml file to do a gobuild and a gotest.

For a proper integration test, we need some kind of of simulation of the CS API. If I remember correctly there is a container that can be used for this purpose? Do you know where I can find it and how to use it for automated testing?
Thanks!

**Pull request merged**
