### PR TITLE
Implement Travis checks

### PR DESCRIPTION
**Pull request by onitake**
This PR adds a Travis-CI script, test cases, and applies `go fmt` to satisfy the formatting check.

It should be merged after Travis is enabled on the Github repository, so we can verify that it's functioning correctly.

See also: https://github.com/apache/cloudstack-kubernetes-provider/pull/8#issuecomment-698182811 .

### CODE REVIEW

**Comment by onitake** [comment]
@rhtyd I created the INFRA ticket here: https://issues.apache.org/jira/projects/INFRA/issues/INFRA-20921
I wasn't sure about all the options, please correct any mistakes that I made.

**Comment by rhtyd** [comment]
Thanks @onitake I'll reply on that as well

**Review by rhtyd — APPROVED** [review]

**Comment by onitake** [comment]
Looks like the infra ticket got approved!
I'll try to do a force push to see if it works.

**Comment by onitake** [comment]
@rhtyd Tests ran through, I think you should merge this now. Thanks!

**Pull request merged**
