### PR TITLE
Update kubernetes libraries

### PR DESCRIPTION
**Pull request by davidjumani**
Fixes https://github.com/apache/cloudstack-kubernetes-provider/issues/20

Updated the Kubernetes framework to v1.18 since 1.19 introduces `cloudprovider.Interface.InstancesV2` which is experimental and could change in v1.20, which might involve additional changes later on
https://github.com/kubernetes/cloud-provider/blob/release-1.19/cloud.go#L56

Added `get_kubernetes_dep.sh` to fetch and tweak the kubernetes framework since simply updating it causes issues :
https://github.com/kubernetes/client-go/issues/741
https://github.com/kubernetes/kubernetes/issues/79384#issuecomment-505725449

### CODE REVIEW

**Comment by davidjumani** [comment]
Tests pass. Good to go @onitake 
```
go test -v ./...
=== RUN   TestReadConfig
--- PASS: TestReadConfig (0.00s)
=== RUN   TestNewCSCloud
    cloudstack_test.go:89: No config found in environment
--- SKIP: TestNewCSCloud (0.00s)
=== RUN   TestLoadBalancer
    cloudstack_test.go:101: No config found in environment
--- SKIP: TestLoadBalancer (0.00s)
PASS
ok      github.com/apache/cloudstack-kubernetes-provider        (cached)
?       github.com/apache/cloudstack-kubernetes-provider/cmd/cloudstack-ccm     [no test files]
```

**Comment by davidjumani** [comment]
@onitake Could you review the changes ?

**Comment by onitake** [comment]
Sorry @davidjumani , this got lost under other stuff.
The framework update script looks very useful indeed!
It was a lot of hassle to manually update the commti hashes in the past.

Aside from that, this looks good to me.

**Comment by davidjumani** [comment]
@rhtyd Could you merge this? Thanks!

**Pull request merged**
