### PR TITLE
Improved Ingress Controller example to be clearer and more complete

### PR DESCRIPTION
**Pull request by onitake**
This PR expands the Ingress Controller example to a minimal viable config.

It should illustrate the concept better and explain how to configure Træfik to use the TCP-Proxy protocol.

### CODE REVIEW

**Comment by joschi36** [comment]
maybe we could use the nginx-ingress to be a little more "standard/basic*?

**Comment by onitake** [comment]
What's wrong with Træfik? :smiley: 

I think an example for both would be even better. Feel free to add one to the PR!

**Comment by rhtyd** [comment]
@onitake can we get someone to lgtm this. Happy to merge is someone can review the change.

**Comment by onitake** [comment]
Please don't merge yet, we still have to test the changes in 4aa96db

**Comment by rhtyd** [comment]
Okay @onitake let me know when you're done and if you can get someone to review your changes. Thanks.

**Comment by onitake** [comment]
@joschi36 please review and update the example with the results from your recent experiments with the nginx ingress controller. Thank you!

**Comment by rhtyd** [comment]
Ping @onitake - any update on this?

**Review by joschi36 — APPROVED** [review]

**Comment by rhtyd** [comment]
@onitake can you advise when this is ready for merging, thnx

**Comment by onitake** [comment]
@rhtyd I think it's ok to merge this now.
The example should be good enough to get people started.

**Pull request merged**
