### PR TITLE
Update to Kubernetes 1.24.12 + Use Go 1.19

### PR DESCRIPTION
**Pull request by hrak**
This PR is a continuation of the work in #32 and contains the following changes:

- Use Go 1.19
- Update Kubernetes deps to ~1.26.2~ 1.24.12
- Move the cloudstack-go dep to its new home in the apache org (and update to v2.15.0)
- switch to klog v2

I can provide a test container image if needed.

### CODE REVIEW

**Comment by joschi36** [comment]
If you have the time I would really appreciate if there is a version in between. For instance 1.24.

**Comment by hrak** [comment]
> If you have the time I would really appreciate if there is a version in between. For instance 1.24.

yeah i was afraid of that already, i suddenly realized that compiling this against 1.26 probably means losing compatibility with 1.24 and 1.25 which are still supported. I will get on it!

**Comment by hrak** [comment]
Updated PR to use Kubernetes v1.24.11 instead

**Comment by hrak** [comment]
Ship it? Or does anything else need to happen?

**Comment by hrak** [comment]
Added a switch to klog v2 + updated PR for k8s 1.24.12

**Comment by rohityadavcloud** [comment]
@davidjumani could you have a quick look and help merge it. 

@RolphH @hrak could you advise what testing you’ve done against any/various versions of CloudStack?

**Comment by hrak** [comment]
> @davidjumani could you have a quick look and help merge it.
> 
> @RolphH @hrak could you advise what testing you’ve done against any/various versions of CloudStack?

We are running this without any issues so far on Cloudstack 4.17. We have some more changes in the pipeline once this is merged.

**Comment by hrak** [comment]
> We are running this without any issues so far on Cloudstack 4.17. We have some more changes in the pipeline once this is merged.

Well, maybe i should clarify: The part that works is the loadbalancer/firewall rules part. Most of the logic surrounding instance metadata is broken ever since this was turned into and external cloud provider. `GetZone` assumes this is running inside kubelet and that hostname=instance hostname, but it isn't, since the provider runs in a pod, causing it to try to look up the instance based on the pod hostname:

```
I0414 07:08:41.827320       1 cloudstack.go:175] GetZone called from /go/src/github.com/apache/cloudstack-kubernetes-provider/cloudstack_instances.go#198
E0414 07:08:41.874064       1 node_controller.go:220] error syncing 'k8s-mgmt-cp-dev-02': failed to get instance metadata for node k8s-mgmt-cp-dev-02: could not find instance for retrieving the zone: No match found for cloud-controller-manager-789b9fb546-dg46l: &{Count:0 VirtualMachines:[]}, requeuing
```

Then there are issues with ProviderID, since the provider is currently called `external-cloudstack` and should probably be called `cloudstack`, so the [logic here](https://github.com/kubernetes/cloud-provider/blob/322c087411fe027de06291c6ad974ed7bcbf2eea/cloud.go#L114) matches the kubelet arguments `--cloud-provider=external --provider-id=cloudstack:///8411c37d-8d63-4920-8cb2-01fa512c3377` in the same way that this works for f.e. the Openstack CCM.

I am working on fixes for all these issues but i would really like to get this in first.

**Comment by rohityadavcloud** [comment]
Thanks @RolphH @hrak I'll merge this based on your tests and feedback. Pl do followup with other changes you think we need for the codebase.

**Pull request merged**
